import Head from 'next/head'
import styles from '../styles/Home.module.css'
function App(){

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div style={{display: "block"}}>
                    test
                </div>
            </main>
        </div>
    )
}

export default App
